stages:
  - build
  - test

build:linux:
  image: rust:latest
  stage: build
  before_script:
    - apt-get update -qq
    - apt-get install -qq build-essential curl git
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
    - rustup component add rustfmt-preview
  script:
    - cargo build --release
    - cargo clippy -- -D warnings
    - cargo fmt -- --check
  artifacts:
    paths:
      - target/release/calc
  cache:
    paths:
      - cargo/
      - target/

build:redox:
  image: redoxos/redoxer
  stage: build
  before_script:
    - apt-get update 
  script:
    - redoxer build --verbose
  cache:
    paths:
      - cargo/
      - target/

rustdoc:linux:
  image: rust:latest
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc

test:linux:
  image: rust:latest
  stage: test
  before_script:
    - apt-get update -qq
    - apt-get install -qq build-essential curl git
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  dependencies:
    - build:linux
  script:
    - cargo test

test:redox:
  image: redoxos/redoxer
  stage: test
  before_script:
    - apt-get update 
  dependencies:
    - build:redox
  script:
    - redoxer test +nightly --verbose
